environment:
  CONDA_INSTALL_LOCN: "C:\\conda"
  CMD_IN_ENV: cmd /E:ON /V:ON /C Obvious-CI\scripts\obvci_appveyor_python_build_env.cmd

  BINSTAR_TOKEN:
    secure: eNFZ6uLsFUgtwjXf6n/vayT97T4sSX1nG3iv8Hfp2vWKIZJIQ6jmCeL/agYmnbiX

  matrix:
    - TARGET_ARCH: "x64"
      CONDA_PY: "27"
      CONDA_NPY: "19"

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

install:
    - cmd: assoc .py
    - cmd: ftype Python.File
    - cmd: git submodule update --init --recursive
    - cmd: rmdir C:\cygwin /s /q
    - cmd: python Obvious-CI\bootstrap-obvious-ci-and-miniconda.py %CONDA_INSTALL_LOCN% %TARGET_ARCH% %CONDA_PY:~0,1% --without-obvci --miniconda-version latest
    - cmd: SET PATH=%CONDA_INSTALL_LOCN%;%CONDA_INSTALL_LOCN%\Scripts;%PATH%

    - cmd: conda config --set always_yes true
    - cmd: conda update --quiet conda
    - cmd: conda config --add channels astropy
    - cmd: conda install --file appveyor_pinned.txt
    - cmd: conda list -e
    # Install obvious-ci; run 2to3 first if the build is python 3.
    - cmd: cd Obvious-CI & (if %CONDA_PY:~0,1%==3 2to3 -w .) & python setup.py install & cd ..
    - cmd: assoc .py
    - cmd: ftype Python.File

# Skip .NET project specific build phase.
build: off

test_script:
    - "%CMD_IN_ENV% python affiliate-builder\\prepare_packages.py requirements.txt"
    - if exist recipes %CMD_IN_ENV% obvci_conda_build_dir.py recipes astropy
    - if exist bdist_conda %CMD_IN_ENV% build_bdist.bat

on_success:
    - "if exist bdist_conda %CMD_IN_ENV% python affiliate-builder\\upload_bdists.py"
